### ISSUE TITLE
[bug] - Collection -  Bulk Import With CSV not work

### ISSUE THREAD

**Issue by K119928** [zzf7ktx/shopify-tools#143]
![Capture](https://github.com/zzf7ktx/shopify-tools/assets/160218410/2f55cece-6803-4807-8ab5-2490bace16e4)

**Comment by zzf7ktx** [comment]
![image](https://github.com/zzf7ktx/shopify-tools/assets/41227962/873bf029-1088-4e49-8791-c6edc77c2b9d)
File example
